name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOSTNAME_BBIZ }}
          username: ${{ secrets.SSH_USERNAME_BBIZ }}
          password: ${{ secrets.SSH_PASSWORD_BBIZ }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /var/www/olmat-backoffice
            git reset --hard
            git pull
            yarn install
            yarn build
            pm2 stop production.config.js
            pm2 start production.config.js
